import type {ReactNode} from "react";
const logoUrl=()=>`${(import.meta as ImportMeta&{env:{BASE_URL:string}}).env.BASE_URL}brand/logo-zh-full.svg`;
function Frame({number,label,title,takeaway,tone="cream",children}:{number:number;label:string;title:string;takeaway:string;tone?:string;children:ReactNode}){return <main className={`slide slide-${tone}`} data-deck-page data-qa-safe-zone><div className="topline"/><header className="studio-header"><img className="brand-logo" src={logoUrl()} alt="匠人学院"/><span className="course-label">CCDV-F · Final Review</span></header><section className="lesson-board"><div className="board-meta"><span className="eyebrow">第十课 · {label}</span><span className="progress">{String(number).padStart(2,"0")} / 18</span></div><section className="chapter-heading"><h1>{title}</h1></section><section className="slide-body">{children}</section><aside className="takeaway"><span>本页结论</span><strong>{takeaway}</strong></aside><footer><span>Claude Certified Developer – Foundations</span><strong>JR Course Studio · Exam Prep</strong></footer></section></main>}
function Format(){return <Frame number={1} label="EXAM CLOCK" title="53 题，不是 60 题" takeaway="120 分钟 ÷ 53 = 每题 2 分 15 秒；按 60 题训练会把节奏练错。"><div className="prep-clock"><section><span>QUESTIONS</span><strong>53</strong></section><i>÷</i><section><span>MINUTES</span><strong>120</strong></section><i>=</i><section className="pace"><span>PACE</span><strong>2:15</strong><b>per question</b></section><aside>NO SCENARIO QUESTION GROUPS · 每题独立</aside></div></Frame>}
function DomainWeights(){return <Frame number={2} label="DOMAIN PRIORITY" title="前三域吃掉 64.6%" takeaway="时间不够，先死磕 D2 + D5 + D1。" tone="rose"><div className="prep-bars">{[["D2 Applications","33.1","100"],["D5 Model","16.8","51"],["D1 Agents","14.7","44"],["D6 Prompt","11.0","33"],["D8 Tools","10.6","32"],["D7 Security","8.1","24"],["D3 Code","3.1","9"],["D4 Eval","2.6","8"]].map((r,i)=><article className={i<3?"top":""} key={r[0]}><span>{r[0]}</span><i style={{width:`${r[2]}%`}}/><b>{r[1]}%</b></article>)}</div></Frame>}
function TopSkills(){return <Frame number={3} label="SUBSKILL RANK" title="最高两项都在 D2，而且都是工程基本功" takeaway="Application Design 8.6% + Software Engineering 7.4% = 16%。" tone="sky"><div className="prep-podium"><article className="p2"><span>#2</span><strong>Software Engineering</strong><b>7.4%</b></article><article className="p1"><span>#1</span><strong>Claude Application Design</strong><b>8.6%</b></article><article className="p3"><span>#3</span><strong>Claude API Mechanics</strong><b>6.8%</b></article></div><aside className="prep-fact">纯软件工程相关合计 13.6% &gt; 整个 Tools &amp; MCPs 10.6%</aside></Frame>}
function TimeBudget(){return <Frame number={4} label="40-HOUR PLAN" title="复习时间也要按权重路由" takeaway="Claude Code 只给 1.5 小时；Applications 给 13 小时。" tone="lavender"><div className="prep-time">{[["D2","13h","33.1%"],["D5","7h","16.8%"],["D1","6h","14.7%"],["D6","4.5h","11.0%"],["D8","4h","10.6%"],["D7","3h","8.1%"],["D3","1.5h","3.1%"],["D4","1h","2.6%"]].map((r,i)=><article className={i===0?"major":i>5?"minor":""} key={r[0]}><span>{r[0]}</span><strong>{r[1]}</strong><b>{r[2]}</b></article>)}</div></Frame>}
function TwoWeeks(){return <Frame number={5} label="LAST 14 DAYS" title="最后两周：按分值倒推，不按兴趣复习" takeaway="-2 周补 D2；-1 周扫 D5/D1/D6/D8；最后 3 天收尾低权重域。" tone="rose"><div className="prep-road"><article><span>WEEK -2</span><strong>D2</strong><p>Design · Software · API</p><b>23%+</b></article><i>→</i><article><span>WEEK -1</span><strong>D5 · D1 · D6 · D8</strong><p>Token · Loop · Context · Tools</p><b>52.1%</b></article><i>→</i><article><span>DAY -3</span><strong>D7 · D3 · D4</strong><p>Security · Code · Debug</p><b>13.8%</b></article></div></Frame>}
function FourTraps(){return <Frame number={6} label="WRONG ANSWER DNA" title="四种错误答案，反复换皮出现" takeaway="过度工程、无视约束、下游补丁、用 Prompt 解决确定性问题。" tone="sky"><div className="prep-four">{[["01","OVERBUILD","小问题上重架构"],["02","IGNORE CONSTRAINT","答案好但违反题干"],["03","DOWNSTREAM PATCH","让报警消失但不修根因"],["04","PROMPT AS CONTROL","用概率请求保证安全"]].map(r=><article key={r[0]}><span>{r[0]}</span><strong>{r[1]}</strong><p>{r[2]}</p></article>)}</div></Frame>}
function Overbuild(){return <Frame number={7} label="TRAP 01" title="Most effective first step：先选便宜、对症的动作" takeaway="工具选错先扩 description；固定三步流程用 workflow。" tone="lavender"><div className="prep-scale"><section><span>PROBLEM</span><strong>两个工具经常选混</strong></section><div><article><span>轻</span><strong>补 description</strong><b>✓ minutes</b></article><article><span>重</span><strong>Routing classifier</strong><b>✕ infra + data</b></article></div></div></Frame>}
function Constraints(){return <Frame number={8} label="TRAP 02" title="题干约束是淘汰器，不是背景故事" takeaway="用户在等就砍 Batch；内网代码砍 Managed Agents；不降准确率砍小模型。" tone="rose"><div className="prep-constraints">{[["REALTIME","Batch API","最长 24h"],["BEDROCK / VERTEX","Batch API","平台不支持"],["CODE STAYS INTERNAL","Managed Agents","沙箱在外部"],["NO QUALITY LOSS","smaller model","违反准确率约束"],["TIGHT SLA","extra router","多一次往返"],["CROSS HOST","shared package","够不着 Claude Code"]].map(r=><article key={r[0]}><span>{r[0]}</span><s>{r[1]}</s><b>{r[2]}</b></article>)}</div></Frame>}
function SourceFix(){return <Frame number={9} label="TRAP 03" title="“忽略、吞掉、跳过”常常在掩盖真故障" takeaway="空结果误标 error，要回工具源头修；不要让 coordinator 忽略所有 error。" tone="sky"><div className="prep-source"><section><span>SYMPTOM</span><strong>found: false → is_error</strong></section><div><article className="bad"><b>DOWNSTREAM</b><p>忽略所有 is_error</p><p>try/catch 吞掉</p><strong>真故障一起消失</strong></article><article className="good"><b>SOURCE FIX</b><p>空结果 is_error:false</p><p>瞬时错误 retryable:true</p><strong>语义恢复正确</strong></article></div></div></Frame>}
function Deterministic(){return <Frame number={10} label="TRAP 04" title="必须保证的事，不要交给模型“记得”" takeaway="JSON 用 Schema；授权用代码；危险动作用 PreToolUse。" tone="lavender"><div className="prep-control">{[["VALID JSON","Prompt: always JSON","output_config.format"],["VERIFY BEFORE REFUND","Prompt reminder","PreToolUse deny"],["ADMIN DELETE","User claims role","server permission"],["NO INJECTION ACTION","ignore data instructions","least privilege"],["NO TRUNCATION","please be complete","raise max_tokens"]].map(r=><article key={r[0]}><span>{r[0]}</span><s>{r[1]}</s><strong>{r[2]}</strong></article>)}</div></Frame>}
function Repeats(){return <Frame number={11} label="CROSS-DOMAIN" title="同一事实跨域重复，出题概率最高" takeaway="${VAR}、缓存前缀、模型迁移在三个域反复出现。" tone="rose"><div className="prep-repeat">{[["${VAR}","D2 · D3 · D7"],["Cache prefix","D2 · D5 · D6"],["Model migration","D2 · D4 · D5"],["Instruction carrier","D2 · D3 · D6"],["Pre vs Post","D1 · D7"],["Empty ≠ Error","D4 · D8"],["Least privilege","D7 · D8"],["Subagent isolation","D1 · D6"]].map(r=><article key={r[0]}><strong>{r[0]}</strong><span>{r[1]}</span></article>)}</div></Frame>}
function Numbers(){return <Frame number={12} label="NUMBERS" title="硬数字别靠现场推" takeaway="720 是量表分，不是 72%；Batch 省 50%，Cache Read 约 0.1×。" tone="sky"><div className="prep-numbers">{[["53","题"],["120","分钟"],["720","量表分"],["12","个月有效"],["14/30/90","重考冷却"],["4","缓存断点"],["20","block 回溯"],["50%","Batch 折扣"],["24h","Batch 窗口"],["2","SDK retries"]].map(r=><article key={r[0]}><strong>{r[0]}</strong><span>{r[1]}</span></article>)}</div></Frame>}
function StopReasons(){return <Frame number={13} label="STOP REASONS" title="循环只认协议状态，不猜文本语气" takeaway="end_turn 是唯一正常出口；max_tokens 是失败；pause_turn 原样重发。" tone="lavender"><div className="prep-stop">{[["end_turn","EXIT","正常结束"],["tool_use","EXECUTE","回 tool_result"],["max_tokens","FAIL","提高上限 / streaming"],["pause_turn","REPLAY","原样重发 response.content"],["refusal","BRANCH","先判再读 content"]].map(r=><article key={r[0]}><code>{r[0]}</code><strong>{r[1]}</strong><span>{r[2]}</span></article>)}</div></Frame>}
function Http(){return <Frame number={14} label="HTTP TRIAGE" title="429 / 500 / 529 / 连接错误才走重试" takeaway="400–413 的请求、凭证、权限、ID 与大小问题，原样重试没用。" tone="rose"><div className="prep-http"><section><span>DO NOT RETRY</span>{[["400","bad request"],["401","credentials"],["403","permission"],["404","model id"],["413","too large"]].map(r=><b key={r[0]}><i>{r[0]}</i>{r[1]}</b>)}</section><section className="retry"><span>RETRY</span>{[["429","retry-after + jitter"],["500","server"],["529","overloaded"],["NET","connection"]].map(r=><b key={r[0]}><i>{r[0]}</i>{r[1]}</b>)}</section></div></Frame>}
function Breaking(){return <Frame number={15} label="MIGRATION" title="有些旧参数直接 400，有些行为静默变" takeaway="升级必须 pin → review → eval → 重新计数与校准。" tone="sky"><div className="prep-breaking"><section><span>HARD 400</span><b>temperature / top_p / top_k</b><b>thinking budget_tokens</b><b>assistant prefill</b><b>top-level output_format</b></section><section><span>SILENT CHANGE</span><b>thinking display → omitted</b><b>省略 thinking ≠ adaptive</b><b>tokenizer 改变</b><b>更字面遵循旧指令</b></section></div></Frame>}
function McpTools(){return <Frame number={16} label="TOOLS QUICK SHEET" title="四选一靠复用面；MCP 三件套靠控制方" takeaway="官方已有 Builtin；单 App Custom；知识 Skill；跨 Host MCP。" tone="lavender"><div className="prep-tools"><section>{[["BUILTIN","official"],["CUSTOM","one app"],["SKILL","knowledge"],["MCP","cross host"]].map(r=><b key={r[0]}><strong>{r[0]}</strong>{r[1]}</b>)}</section><section>{[["TOOLS","model controls"],["RESOURCES","app controls"],["PROMPTS","user controls"]].map(r=><b key={r[0]}><strong>{r[0]}</strong>{r[1]}</b>)}</section><aside>host → one client per server · stdio local · Streamable HTTP remote</aside></div></Frame>}
function EightLines(){return <Frame number={17} label="8 DOMAINS" title="八个域，各保留一个判断句" takeaway="不是背百科，而是让每道题先落到正确控制层。" tone="rose"><div className="prep-eight">{[["D1","简单优先；Loop 看 stop_reason"],["D2","在正确层解决；约束是钥匙"],["D3","层级 + settings + headless"],["D4","HTTP 200 是分界线"],["D5","先不降质量的成本刀"],["D6","约束放对层；验证自信输出"],["D7","请求不是控制"],["D8","回源头；复用面决定选型"]].map(r=><article key={r[0]}><span>{r[0]}</span><strong>{r[1]}</strong></article>)}</div></Frame>}
function ExamLoop(){return <Frame number={18} label="EXAM DAY" title="每道题用同一个 20 秒决策循环" takeaway="圈约束 → 定位层 → 排除四类陷阱 → 选成比例第一步 → 卡住就标记。" tone="sky"><div className="prep-loop">{[["01","CIRCLE","实时 / 成本 / 平台 / 复用"],["02","LOCATE","集成 / 模型 / 工具 / 安全"],["03","ELIMINATE","四类错误答案"],["04","CHOOSE","最便宜、最对症、回源头"],["05","MOVE","超时就标记，保护后两题"]].map(r=><article key={r[0]}><span>{r[0]}</span><strong>{r[1]}</strong><p>{r[2]}</p></article>)}</div></Frame>}
export const chapterSlides=[<Format key="format"/>,<DomainWeights key="domain-weights"/>,<TopSkills key="top-skills"/>,<TimeBudget key="time-budget"/>,<TwoWeeks key="two-weeks"/>,<FourTraps key="four-traps"/>,<Overbuild key="overbuild"/>,<Constraints key="constraints"/>,<SourceFix key="source-fix"/>,<Deterministic key="deterministic"/>,<Repeats key="repeats"/>,<Numbers key="numbers"/>,<StopReasons key="stop-reasons"/>,<Http key="http"/>,<Breaking key="breaking"/>,<McpTools key="mcp-tools"/>,<EightLines key="eight-lines"/>,<ExamLoop key="exam-loop"/>];
