export const classroomConfig = {
  bridgeVersion: 1,
  deckId: "vibe-coding-master-l1",
  title: "Vibe Coding 大师课 · 第一节课",
  slideCount: 40,
  sourceVersion: "0.1.0",
  slideTitles: [
    "Vibe Coding 大师课",
    "今晚内容总览",
    "学员自我介绍",
    "什么是 Vibe Coding",
    "AI coding for everything",
    "金鱼记忆钩子",
    "300 人真实数据",
    "SSO 一小时标尺",
    "不会 Vibe Coding 的代价",
    "真实项目与高权限训练",
    "传统 SDLC",
    "Agent Development Lifecycle",
    "Multi-Agent 与 Worktree",
    "8 周路线图",
    "Phase 1 · 基础能力",
    "Phase 2 · 产品与 PRD",
    "Phase 3 · 多 Agent 协作",
    "Phase 4 · 企业记忆系统",
    "会持续进化的课程大纲",
    "Single Source of Truth",
    "没有 SoT 的混乱",
    "SoT 案例题",
    "SoT 案例答案",
    "SoT 决策阶梯",
    "先确定 SoT",
    "一份 SoT 长出多种产物",
    "个人 AI OS",
    "AI OS 的两层结构",
    "记忆系统 Four C",
    "从原始资料到交付物",
    "为什么使用 Markdown 与 YAML",
    "真实个人 AI OS",
    "企业 AI OS",
    "现场 Demo · 第二大脑",
    "动手建立 Experiences",
    "课后作业",
    "理解检查",
    "同时指挥 10 个 Agent",
    "Vibe Coding 适合每个人",
    "下一步"
  ],
} as const;
