import type {ReactNode} from "react";
const logoUrl=()=>`${(import.meta as ImportMeta&{env:{BASE_URL:string}}).env.BASE_URL}brand/logo-zh-full.svg`;
function Frame({number,label,title,takeaway,tone="cream",children}:{number:number;label:string;title:string;takeaway:string;tone?:string;children:ReactNode}){return <main className={`slide slide-${tone}`} data-deck-page data-qa-safe-zone><div className="topline"/><header className="studio-header"><img className="brand-logo" src={logoUrl()} alt="匠人学院"/><span className="course-label">CCDV-F · Tools &amp; MCPs</span></header><section className="lesson-board"><div className="board-meta"><span className="eyebrow">第九课 · {label}</span><span className="progress">{String(number).padStart(2,"0")} / 18</span></div><section className="chapter-heading"><h1>{title}</h1></section><section className="slide-body">{children}</section><aside className="takeaway"><span>本页结论</span><strong>{takeaway}</strong></aside><footer><span>Claude Certified Developer – Foundations</span><strong>JR Course Studio · Domain 8</strong></footer></section></main>}
const cards=(rows:string[][],cls="tool-cards")=><div className={cls}>{rows.map((r,i)=><article className={`t${i+1}`} key={r.join("")}><span>{r[0]}</span><strong>{r[1]}</strong>{r[2]&&<p>{r[2]}</p>}</article>)}</div>;
function Weight(){return <Frame number={1} label="WEIGHT MAP" title="10.6%：八成在 Tool 与选型，不在 MCP 代码" takeaway="Tool Implementation 4.4% + Agentic Customization 4.1%。"><div className="tool-weight"><section><span>DOMAIN 8</span><strong>10.6%</strong><b>≈ 6 题</b></section><div>{[["Tool Implementation","4.4%","88"],["Agentic Customization","4.1%","82"],["MCP Development","2.1%","42"]].map(r=><article key={r[0]}><header><b>{r[0]}</b><span>{r[1]}</span></header><i style={{width:`${r[2]}%`}}/></article>)}</div></div></Frame>}
function Description(){return <Frame number={2} label="TOOL DESCRIPTION" title="模型对工具的全部业务认知，就在 description 里" takeaway="至少写做什么、何时用、何时不用、参数格式与不返回什么。" tone="rose"><div className="tool-desc"><section><span>BAD</span><strong>“查会员资料”</strong><p>模型只能猜</p></section><i>→</i><section className="good"><span>GOOD · 4 PARTS</span><b>做什么 / 何时用</b><b>何时不用 / 转向哪个工具</b><b>参数含义与格式</b><b>重要限制与不返回项</b></section></div></Frame>}
function Symmetric(){return <Frame number={3} label="ROUTING BOUNDARY" title="相近工具要互相写“不要用我”" takeaway="给 A 指向 B，也要给 B 指回 A；对称边界减少双向误路由。" tone="sky"><div className="tool-sym"><section><span>query_member_profile</span><strong>账户 · 到期 · 邮箱</strong><b>不返回进度 → 用 learning_progress</b></section><i>↔</i><section><span>query_learning_progress</span><strong>课次 · 完课率 · 作业</strong><b>不返回账户 → 用 member_profile</b></section></div></Frame>}
function Schema(){return <Frame number={4} label="INPUT SCHEMA" title="Schema 是免费的参数护栏" takeaway="pattern、enum、format 先挡错参；required 只放真正必填。" tone="lavender"><div className="tool-schema"><code>{`member_id: {\n type: "string",\n pattern: "^M[0-9]{8}$",\n description: "不是邮箱或手机号"\n}`}</code><section><b>pattern</b><b>enum</b><b>format</b><strong>FREE GUARDRAILS</strong></section><aside>required 太长 → 信息缺失时更容易编造</aside></div></Frame>}
function Granularity(){return <Frame number={5} label="TOOL GRANULARITY" title="六个 GitHub 工具总选错？先合并，不是再写六篇作文" takeaway="相关动作合成一个 action 参数；跨服务用命名空间。" tone="rose"><div className="tool-merge"><section>{["create_pr","review_pr","merge_pr","close_pr"].map(x=><b key={x}>{x}</b>)}</section><i>MERGE</i><section className="one"><strong>github_pr</strong><code>action: create | review | merge | close</code></section></div></Frame>}
function ToolChoice(){return <Frame number={6} label="TOOL CHOICE" title="Auto、Any、Tool、None：控制强度逐级变化" takeaway="必须建单但类别未知用 any；固定首步用 tool；循环默认 auto。" tone="sky"><div className="tool-choice">{[["AUTO","可不调 / 自选","Agent loop"],["ANY","必须调 / 自选","多 schema 建单"],["TOOL","必须调指定","固定 triage 首步"],["NONE","禁止工具","纯文本轮"]].map(r=><article key={r[0]}><span>{r[0]}</span><strong>{r[1]}</strong><b>{r[2]}</b></article>)}</div></Frame>}
function AnyLoop(){return <Frame number={7} label="LOOP TRAP" title="把 any 挂在整个 Loop 上，模型永远不能收尾" takeaway="any/tool 只用于单轮强制；之后切回 auto，允许 end_turn。" tone="lavender"><div className="tool-loop"><article><span>TURN 1</span><strong>tool_choice: any</strong><b>必须建单 ✓</b></article><article><span>TURN 2</span><strong>仍然 any</strong><b>本该回答，却又被逼调用</b></article><article className="fix"><span>FIX</span><strong>switch → auto</strong><b>end_turn ✓</b></article></div></Frame>}
function ErrorMatrix(){return <Frame number={8} label="ERROR SEMANTICS" title="is_error 只说坏没坏；category 才说怎么办" takeaway="Rate limit 重试；输入错改参；Auth 升级；空结果不是错误。" tone="rose"><div className="tool-errors">{[["TRANSIENT","is_error: true","retryable: true"],["BAD INPUT","is_error: true","fix arguments"],["EMPTY","is_error: false","found: false"],["AUTH","is_error: true","escalate"]].map((r,i)=><article className={i===2?"empty":""} key={r[0]}><span>{r[0]}</span><strong>{r[1]}</strong><b>{r[2]}</b></article>)}</div></Frame>}
function EmptyResult(){return <Frame number={9} label="EMPTY ≠ ERROR" title="“查过了，没有”是完整答案，不是系统故障" takeaway="返回 found:false；误标 is_error 会让 agent 重试到死。" tone="sky"><div className="tool-empty"><section><span>QUERY OK</span><strong>0 matches</strong><code>{`{ "found": false }`}</code></section><i>≠</i><section className="failure"><span>QUERY FAILED</span><strong>timeout / auth</strong><code>{`{ "is_error": true }`}</code></section></div></Frame>}
function ClientServer(){return <Frame number={10} label="EXECUTION SIDE" title="客户端工具你执行；服务端工具 Anthropic 执行" takeaway="Bash/Text Editor 是内建 schema、客户端执行；服务端失败可能 HTTP 200。" tone="lavender"><div className="tool-side"><section><span>CLIENT-SIDE</span><b>Custom tools</b><b>Bash / Text editor</b><p>你的代码跑 loop</p></section><section><span>SERVER-SIDE</span><b>Web search / fetch</b><b>Code execution</b><p>结果同一 response 返回</p></section><aside><strong>HTTP 200</strong><span>仍需检查 result content 的 error_code</span></aside></div></Frame>}
function FourWays(){return <Frame number={11} label="CUSTOMIZATION" title="Builtin、Custom、Skill、MCP：判据是能力类型与复用面" takeaway="官方已有用 Builtin；单 App 用 Custom；知识用 Skill；跨 Host 用 MCP。" tone="rose"><div className="tool-four">{[["BUILTIN","官方现成能力","web / code / files"],["CUSTOM","单一 App 函数","你的代码执行"],["SKILL","知识与流程","按相关性加载"],["MCP","跨 App / Host","独立 server"]].map(r=><article key={r[0]}><span>{r[0]}</span><strong>{r[1]}</strong><p>{r[2]}</p></article>)}</div></Frame>}
function DecisionTree(){return <Frame number={12} label="SELECTION TREE" title="先问“是什么”，再问“给几个 Host 用”" takeaway="MCP 不是更高级；单 App 套 MCP 只是多一层协议和进程。" tone="sky"><div className="tool-tree"><header>ADD CAPABILITY</header><section><article><span>官方已有？</span><strong>BUILTIN</strong></article><article><span>知识/流程？</span><strong>SKILL</strong></article><article><span>单 App 执行？</span><strong>CUSTOM TOOL</strong></article><article><span>跨 App / Host？</span><strong>MCP</strong></article></section></div></Frame>}
function McpRoles(){return <Frame number={13} label="MCP ARCHITECTURE" title="一个 Server，对应一个 Client 和一条专属连接" takeaway="Host 管多个 Client；不是一个 Client 连多个 Server，也不是 Server 主动连 Host。" tone="lavender"><div className="tool-roles"><article className="host"><span>HOST</span><strong>Claude App</strong></article><div>{[1,2,3].map(n=><b key={n}>CLIENT {n}</b>)}</div><div>{[1,2,3].map(n=><b key={n}>SERVER {n}</b>)}</div></div></Frame>}
function Transports(){return <Frame number={14} label="TRANSPORT" title="同机用 stdio，跨网络用 Streamable HTTP" takeaway="Data layer 始终是 JSON-RPC 2.0；transport 只决定怎么传。" tone="rose"><div className="tool-transport"><section><span>LOCAL</span><strong>stdio</strong><p>stdin / stdout · 无网络开销</p></section><section><span>REMOTE</span><strong>Streamable HTTP</strong><p>POST + optional SSE · HTTP auth</p></section><aside>OLD SSE TRANSPORT → DEPRECATED</aside></div></Frame>}
function Primitives(){return <Frame number={15} label="MCP PRIMITIVES" title="Tools 给行动力，Resources 给可见性" takeaway="Tool 由模型控制；Resource 由应用控制；Prompt 由用户显式调用。" tone="sky"><div className="tool-primitives">{[["TOOLS","DO","模型控制","执行函数"],["RESOURCES","SEE","应用控制","只读上下文"],["PROMPTS","START","用户控制","交互模板"]].map(r=><article key={r[0]}><span>{r[0]}</span><strong>{r[1]}</strong><b>{r[2]}</b><p>{r[3]}</p></article>)}</div></Frame>}
function Scopes(){return <Frame number={16} label="MCP SCOPE" title="团队共享内部 MCP：Project scope + ${VAR}" takeaway=".mcp.json 进 Git；token 由环境变量展开，不明文也不 gitignore 配置。" tone="lavender"><div className="tool-scopes">{[["LOCAL","当前项目 / 仅自己","~/.claude.json"],["PROJECT","当前项目 / 团队共享",".mcp.json ✓"],["USER","所有项目 / 仅自己","~/.claude.json"]].map((r,i)=><article className={i===1?"selected":""} key={r[0]}><span>{r[0]}</span><strong>{r[1]}</strong><b>{r[2]}</b></article>)}<aside><code>Authorization: Bearer ${`\${CONFLUENCE_TOKEN}`}</code></aside></div></Frame>}
function RoutingDebug(){return <Frame number={17} label="ROUTING DEBUG" title="模型选错工具，按成本从低到高排查" takeaway="先扩对称 description，再查 system 冲突；分类器最后才上。" tone="rose"><div className="tool-debug">{[["01","DESCRIPTION","补何时不用 + 互相指路"],["02","SYSTEM","找全局指令抢路由"],["03","FEW-SHOT","边界确实难描述"],["04","MERGE","能力高度重叠"],["05","CLASSIFIER","复杂多系统分流"]].map(r=><article key={r[0]}><span>{r[0]}</span><strong>{r[1]}</strong><b>{r[2]}</b></article>)}</div></Frame>}
function McpQuestion(){return <Frame number={18} label="EXAM QUESTION" title="三个 Host 查同一课程库，还要共享表结构" takeaway="MCP server 提供查询 tools；数据库 schema 作为 resource。" tone="sky"><div className="tool-question"><section><span>3 HOSTS</span><b>客服 Bot</b><b>Slack 助手</b><b>Claude Code</b></section><i>→</i><section><span>MCP SERVER</span><strong>course queries</strong><b>独立维护 · 一处升级</b></section><aside><span>RESOURCE</span><strong>schema://courses</strong><p>只读表结构，摆在 Context 里</p></aside></div></Frame>}
export const chapterSlides=[<Weight key="weight"/>,<Description key="description"/>,<Symmetric key="symmetric"/>,<Schema key="schema"/>,<Granularity key="granularity"/>,<ToolChoice key="tool-choice"/>,<AnyLoop key="any-loop"/>,<ErrorMatrix key="error-matrix"/>,<EmptyResult key="empty-result"/>,<ClientServer key="client-server"/>,<FourWays key="four-ways"/>,<DecisionTree key="decision-tree"/>,<McpRoles key="mcp-roles"/>,<Transports key="transports"/>,<Primitives key="primitives"/>,<Scopes key="scopes"/>,<RoutingDebug key="routing-debug"/>,<McpQuestion key="mcp-question"/>];
