import type { ReactNode } from "react";
const logoUrl = () => new URL("brand/logo-zh-full.svg", window.location.href).href;
function Frame({number,label,title,takeaway,tone="cream",children}:{number:number;label:string;title:string;takeaway:string;tone?:"cream"|"rose"|"lavender"|"sky";children:ReactNode}){return <main className={`slide slide-${tone}`} data-deck-page data-qa-safe-zone><div className="topline"/><header className="studio-header"><img className="brand-logo" src={logoUrl()} alt="匠人学院"/><span className="course-label">CCDV-F · Model Optimization</span></header><section className="lesson-board"><div className="board-meta"><span className="eyebrow">第六课 · {label}</span><span className="progress">{String(number).padStart(2,"0")} / 18</span></div><section className="chapter-heading"><h1>{title}</h1></section><section className="slide-body">{children}</section><aside className="takeaway"><span>本页结论</span><strong>{takeaway}</strong></aside><footer><span>Claude Certified Developer – Foundations</span><strong>JR Course Studio · Domain 5</strong></footer></section></main>}
const cards=(rows:string[][],cls="opt-cards")=><div className={cls}>{rows.map((r,i)=><article key={r.join("")} className={`o${i+1}`}><span>{r[0]}</span><strong>{r[1]}</strong>{r[2]&&<p>{r[2]}</p>}</article>)}</div>;
function DomainWeight(){return <Frame number={1} label="WEIGHT MAP" title="16.8%，但“选模型”不是大头" takeaway="Technical + LLM Fundamentals 合计 11.3%，约占本域三分之二。"><div className="opt-weight"><section><span>DOMAIN 5</span><strong>16.8%</strong><b>≈ 9 题</b></section><div className="weight-bars">{[["Technical Fundamentals","6.1%","61"],["LLM Fundamentals","5.2%","52"],["Cost & Token","2.8%","28"],["Model Selection","2.7%","27"]].map(r=><article key={r[0]}><div><strong>{r[0]}</strong><span>{r[1]}</span></div><i style={{width:`${r[2]}%`}}/></article>)}</div></div></Frame>}
function NonDeterminism(){return <Frame number={2} label="LLM FUNDAMENTALS" title="Temperature = 0，也不是确定性" takeaway="幂等靠代码，稳定格式靠 Schema；别要求模型逐字复现。" tone="rose"><div className="opt-sampling"><div className="token-chain"><span>INPUT</span><i>→</i><b>概率分布</b><i>→</i><strong>采样 Token</strong><i>→</i><b>下一轮</b></div>{cards([["✕","assert full_text == expected","LLM 输出不是固定字符串"],["✓","Schema / Semantic / Failure Rate","验证结构、语义与统计"]],"opt-two")}</div></Frame>}
function TwoCeilings(){return <Frame number={3} label="TOKEN LIMITS" title="两个上限，修法完全不同" takeaway="Context 管输入+输出总量；max_tokens 只管输出。" tone="sky"><div className="opt-ceilings"><article><span>CONTEXT WINDOW</span><strong>INPUT + OUTPUT</strong><p>模型固有属性</p><b>裁剪 · 分块 · Compaction</b></article><article><span>max_tokens</span><strong>OUTPUT ONLY</strong><p>请求参数</p><b>提高上限 · 超长用 Streaming</b></article></div></Frame>}
function TokenCounting(){return <Frame number={4} label="COUNT TOKENS" title="Token 数跟模型走，不跟字符走" takeaway="messages.count_tokens 要带 model、system、messages 和 tools。" tone="lavender"><div className="opt-counter"><div className="wrong"><span>WRONG</span><strong>tiktoken</strong><b>低估 15–20%</b></div><i>→</i><div className="right"><span>RIGHT</span><strong>messages.count_tokens</strong><code>model + system + messages + tools</code></div><aside>模型升级 → 重新估成本、上限与窗口容量</aside></div></Frame>}
function AdaptiveEffort(){return <Frame number={5} label="THINKING" title="Adaptive 决定要不要想，Effort 决定想多深" takeaway="旧 budget_tokens 已移除；高 Effort 必须给足 max_tokens。" tone="rose"><div className="opt-effort"><section><code>thinking: adaptive</code><p>模型决定何时思考</p><code>output_config.effort</code><p>low · medium · high · xhigh · max</p></section><div className="effort-scale"><span>LOW</span><i/><b>HIGH</b><i/><strong>XHIGH</strong><i/><em>MAX</em></div><aside><b>静默坑</b><span>省略 thinking ≠ adaptive</span><span>display 默认 omitted</span><span>预算不足会截断答案</span></aside></div></Frame>}
function ShotStrategy(){return <Frame number={6} label="SHOT STRATEGY" title="例子只用来解释“边界”" takeaway="格式问题用 Schema；工具问题补描述；边界说不清才上 few-shot。" tone="sky">{cards([["ZERO","清晰常见任务","只给指令"],["ONE","锚定单一风格","给 1 个例子"],["MULTI","正反边界难描述","给 3–5 个例子"]],"opt-shots")}</Frame>}
function SdkRest(){return <Frame number={7} label="SDK ↔ REST" title="SDK 是 HTTP 的工程封装" takeaway="类型、认证、重试、异常、SSE 解析与分页，底层仍是 POST /v1/messages。" tone="lavender"><div className="opt-sdk"><article><span>YOUR CODE</span><code>client.messages.create()</code></article><i>SDK</i><article className="http"><span>HTTP</span><code>POST /v1/messages</code><p>x-api-key · anthropic-version · JSON</p></article><aside><strong>认证二选一</strong><span>API key → x-api-key</span><span>OAuth → Bearer</span></aside></div></Frame>}
function SseTopology(){return <Frame number={8} label="STREAM TRANSPORT" title="Claude 这一段固定是 SSE" takeaway="后端到浏览器可选；Claude 到后端是 Server-Sent Events。" tone="sky"><div className="opt-topology"><article><span>BROWSER</span><strong>UI</strong></article><div className="choice"><b>WebSocket</b><b>SSE</b><b>Polling</b><span>你的架构选择</span></div><article><span>YOUR BACKEND</span><strong>Proxy / API</strong></article><div className="fixed"><b>SSE only</b><span>Claude 固定</span></div><article className="claude"><span>ANTHROPIC</span><strong>Claude</strong></article></div></Frame>}
function ModelTriangle(){return <Frame number={9} label="MODEL TIERS" title="质量、延迟、成本，只能挑两个" takeaway="Haiku 做机械任务，Sonnet 做生产默认，Opus 留给真正最难的问题。" tone="rose"><div className="opt-tiers"><article className="haiku"><span>1×</span><strong>HAIKU</strong><p>分类 · 路由 · 简单抽取</p></article><article className="sonnet"><span>≈ 3×</span><strong>SONNET</strong><p>编码 · Agentic · 生产默认</p></article><article className="opus"><span>≈ 5×</span><strong>OPUS</strong><p>长程自主 · 深度推理</p></article></div></Frame>}
function RoutingLatency(){return <Frame number={10} label="TIERED ROUTING" title="省模型成本，会多一次调用延迟" takeaway="80% 简单流量值得路由；500ms SLA 可能不值得。" tone="lavender"><div className="opt-routing"><article><span>QUERY</span><strong>Haiku Router</strong></article><div className="route-split"><i>simple 80%</i><i>complex 20%</i></div><section><article><strong>Haiku</strong><span>低价大流量</span></article><article><strong>Sonnet / Opus</strong><span>复杂请求</span></article></section><aside><b>TRADE-OFF</b><strong>+ 1 次网络与推理延迟</strong></aside></div></Frame>}
function Migration(){return <Frame number={11} label="MODEL MIGRATION" title="有些升级会 400，有些悄悄变行为" takeaway="模型 ID 要 Pin；升级走 Review、Eval、Token 重算和缓存冷启动。" tone="sky"><div className="opt-migration"><section><header>显式破坏</header><span>temperature 移除 → 400</span><span>旧 thinking → 400</span><span>assistant prefill → 400</span></section><section><header>静默破坏</header><span>display 默认 omitted</span><span>分词器变化</span><span>工具调用倾向变化</span></section><aside><b>PIN</b><i>→</i><b>REVIEW</b><i>→</i><b>EVAL</b><i>→</i><b>RECALIBRATE</b></aside></div></Frame>}
function FourKnives(){return <Frame number={12} label="COST ORDER" title="先纯收益，再用质量换成本" takeaway="Caching → Batch → Model Tier → Effort，这个顺序本身就是考点。" tone="rose"><div className="opt-knives">{[["01","Prompt Cache","≈ 0.1× read","不降质量"],["02","Batch","-50%","不降质量 · 等得起"],["03","Model Tier","Haiku / Sonnet","可能降质量"],["04","Effort","high → medium","用智力换 token"]].map((r,i)=><article className={`k${i+1}`} key={r[0]}><span>{r[0]}</span><strong>{r[1]}</strong><b>{r[2]}</b><p>{r[3]}</p></article>)}</div></Frame>}
function CacheEconomics(){return <Frame number={13} label="CACHE ECONOMICS" title="缓存写稍贵，读只要约 0.1×" takeaway="5 分钟第二次回本；1 小时第三次回本。" tone="lavender"><div className="opt-cache-econ"><section><span>5 MIN TTL</span><div><b>WRITE 1.25×</b><i>+</i><b>READ 0.1×</b><i>=</i><strong>1.35×</strong></div><p>2 次普通请求 = 2× → 已回本</p></section><section><span>1 HOUR TTL</span><div><b>WRITE 2×</b><i>+</i><b>READ 0.2×</b><i>=</i><strong>2.2×</strong></div><p>3 次普通请求 = 3× → 第三次回本</p></section></div></Frame>}
function CacheEdges(){return <Frame number={14} label="CACHE FAILURE" title="三个不报错的缓存陷阱" takeaway="短前缀、同时扇出、超过 20 Blocks，都会静默 Miss。" tone="sky">{cards([["MINIMUM PREFIX","低于约 1K–4K token","不缓存、不报错"],["FAN-OUT RACE","并发一起发","先用 1 个请求预热"],["20-BLOCK LOOKBACK","Agent 轮次过长","每约 15 blocks 加断点"]],"opt-cache-edges")}</Frame>}
function UsageAccounting(){return <Frame number={15} label="COST ACCOUNTING" title="input_tokens 不是总输入" takeaway="总输入 = 未缓存 + 缓存写 + 缓存读；三项按各自费率计算。" tone="rose"><div className="opt-usage"><article><span>FULL PRICE</span><strong>input_tokens</strong></article><i>+</i><article><span>WRITE</span><strong>cache_creation</strong></article><i>+</i><article><span>READ</span><strong>cache_read</strong></article><b>= TOTAL INPUT</b></div></Frame>}
function SupportQuestion(){return <Frame number={16} label="QUESTION 01" title="实时客服，每次带 8K 稳定前缀" takeaway="答案：Prompt Caching。用户在等，Batch 被题干排除。" tone="lavender"><div className="opt-question"><aside><span>REALTIME</span><strong>用户在网页上等</strong><span>STABLE PREFIX</span><strong>8,000 tokens</strong></aside><section>{[["A","Batch 省 50%","等不起 24h"],["B","Prompt Caching","✓ 不降质量"],["C","直接换 Haiku","先别交换质量"],["D","砍 max_tokens","没优化输入瓶颈"]].map(r=><article className={r[0]==="B"?"correct":""} key={r[0]}><b>{r[0]}</b><strong>{r[1]}</strong><span>{r[2]}</span></article>)}</section></div></Frame>}
function TranslationQuestion(){return <Frame number={17} label="QUESTION 02" title="长翻译被截断：到底哪个上限？" takeaway="提高 max_tokens，并在超长输出时 Streaming；不是换大 Context。" tone="sky"><div className="opt-final"><section><span>INPUT</span><strong>300 页原文已装入</strong><b>Context OK</b></section><i>→</i><section><span>OUTPUT</span><strong>半句停止</strong><b>stop_reason: max_tokens</b></section><aside><strong>正确动作</strong><p>提高输出上限</p><p>&gt; ~16K → Streaming</p></aside></div></Frame>}
function Recap(){return <Frame number={18} label="RECAP" title="先看硬约束，再做成本交换" takeaway="Caching → Batch → Model Tier → Effort；Context ≠ max_tokens。" tone="rose">{cards([["01","实时排除 Batch","延迟先锁死"],["02","机械任务用 Haiku","不存在智力上限"],["03","先缓存与 Batch","不降质量"],["04","升级必须 Eval","行为会静默变化"],["05","Claude Streaming = SSE","不是 WebSocket"],["06","总输入看三项之和","别只看 input_tokens"]],"opt-recap")}</Frame>}
export const chapterSlides=[<DomainWeight key="domain-weight"/>,<NonDeterminism key="non-determinism"/>,<TwoCeilings key="two-ceilings"/>,<TokenCounting key="token-counting"/>,<AdaptiveEffort key="adaptive-effort"/>,<ShotStrategy key="shot-strategy"/>,<SdkRest key="sdk-rest"/>,<SseTopology key="sse-topology"/>,<ModelTriangle key="model-triangle"/>,<RoutingLatency key="routing-latency"/>,<Migration key="model-migration"/>,<FourKnives key="four-knives"/>,<CacheEconomics key="cache-economics"/>,<CacheEdges key="cache-edge-cases"/>,<UsageAccounting key="usage-accounting"/>,<SupportQuestion key="support-question"/>,<TranslationQuestion key="translation-question"/>,<Recap key="recap"/>];
